[mysqld]
basedir = /usr/local/mysql
datadir = /data/mysql
socket = /tmp/mysql.sock
log-error = /data/mysql/mysql.err
pid-file = /data/mysql/mysql.pid
# 可选配置
port = 3306
#服务端默认字符集为 utf8mb4 （推荐，支持 emoji 和完整 Unicode）。
character-set-server = utf8mb4
# 默认排序规则（MySQL 8 常用），ai = accent insensitive（重音不敏感）ci = case insensitive（大小写不敏感）
collation-server = utf8mb4_0900_ai_ci
max_connections = 1000

[mysql]
#mysql 命令行客户端默认字符集是 utf8，支持表情符号
default-character-set=utf8mb4

[client]
#所有客户端默认用 utf8 连接。
default-character-set=utf8mb4
